# Generated by Django 5.1.4 on 2025-01-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mesaj', models.TextField()),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
